# Generated by Django 5.2.17 on 2026-08-31 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0005_seed_due_diligence_permissions'),
        ('properties', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueDiligenceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('requested_checks', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_due_diligence_requests', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_due_diligence_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_diligence_requests', to='properties.property')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_diligence_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_diligence_requests', to='parties.party')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='due_diligence_requests', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DueDiligenceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('TITLE', 'Title'), ('PARTY', 'Party'), ('GEOSPATIAL', 'Geospatial'), ('PAYMENT', 'Payment'), ('DOCUMENT', 'Document'), ('LEGAL', 'Legal'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFORMATIONAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_diligence_findings', to=settings.AUTH_USER_MODEL)),
                ('due_diligence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='due_diligence.duediligencerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('LOW_RISK', 'Low risk'), ('MEDIUM_RISK', 'Medium risk'), ('HIGH_RISK', 'High risk'), ('BLOCKED', 'Blocked')], max_length=30)),
                ('summary', models.TextField()),
                ('title_summary', models.TextField(blank=True)),
                ('party_summary', models.TextField(blank=True)),
                ('geospatial_summary', models.TextField(blank=True)),
                ('payment_summary', models.TextField(blank=True)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('due_diligence_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_report', to='due_diligence.duediligencerequest')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_risk_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='duediligencerequest',
            index=models.Index(fields=['property', 'status'], name='due_diligen_propert_cf92a0_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencerequest',
            index=models.Index(fields=['transaction', 'status'], name='due_diligen_transac_4999fd_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencerequest',
            index=models.Index(fields=['requested_by_party', 'status'], name='due_diligen_request_c284ef_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencerequest',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='due_diligen_assigne_27450e_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencefinding',
            index=models.Index(fields=['due_diligence_request', 'severity'], name='due_diligen_due_dil_badfee_idx'),
        ),
        migrations.AddIndex(
            model_name='duediligencefinding',
            index=models.Index(fields=['category', 'severity'], name='due_diligen_categor_62042b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreport',
            index=models.Index(fields=['outcome', 'issued_at'], name='due_diligen_outcome_d678cf_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreport',
            index=models.Index(fields=['prepared_by', 'issued_at'], name='due_diligen_prepare_22c7f9_idx'),
        ),
    ]
