# Generated by Django 5.2.17 on 2026-08-25 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('SOLD', 'Sold'), ('CLOSED', 'Closed')], default='DRAFT', max_length=30)),
                ('is_promoted', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('OWNER', 'Owner'), ('AGENT', 'Agent')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='listings.listing')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_relationships', to='parties.party')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'party', 'relationship'), name='unique_listing_party_relationship')],
            },
        ),
    ]
