# Generated by Django 5.2.17 on 2026-08-31 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary_type', models.CharField(choices=[('PARCEL', 'Parcel'), ('BUILDING_FOOTPRINT', 'Building footprint'), ('ACCESS_PATH', 'Access path'), ('OTHER', 'Other')], default='PARCEL', max_length=30)),
                ('source_type', models.CharField(choices=[('OWERU_ESTABLISHED', 'Established by Oweru'), ('USER_SUPPLIED', 'Supplied by user'), ('AUTHORITY_OBTAINED', 'Obtained from authority')], max_length=30)),
                ('coordinates', models.JSONField(default=list)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('area_variance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_property_boundaries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'is_current'], name='geospatial__propert_7979d9_idx'), models.Index(fields=['boundary_type', 'source_type'], name='geospatial__boundar_45417d_idx'), models.Index(fields=['captured_by', 'created_at'], name='geospatial__capture_acb25d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyLocationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_type', models.CharField(choices=[('OWERU_ESTABLISHED', 'Established by Oweru'), ('USER_SUPPLIED', 'Supplied by user'), ('AUTHORITY_OBTAINED', 'Obtained from authority')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_location_records', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_records', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'is_primary'], name='geospatial__propert_180e10_idx'), models.Index(fields=['captured_by', 'created_at'], name='geospatial__capture_432716_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.CharField(choices=[('BOUNDARY_CONFLICT', 'Boundary conflict'), ('ENCROACHMENT', 'Encroachment'), ('FLOOD', 'Flood'), ('ACCESS', 'Access'), ('UTILITY', 'Utility'), ('ZONING', 'Zoning'), ('ENVIRONMENTAL', 'Environmental'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('source_type', models.CharField(choices=[('OWERU_ESTABLISHED', 'Established by Oweru'), ('USER_SUPPLIED', 'Supplied by user'), ('AUTHORITY_OBTAINED', 'Obtained from authority')], max_length=30)),
                ('description', models.TextField()),
                ('mitigation_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_risks', to='properties.property')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_site_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'severity'], name='geospatial__propert_3b8f03_idx'), models.Index(fields=['risk_type', 'severity'], name='geospatial__risk_ty_0695ff_idx'), models.Index(fields=['recorded_by', 'created_at'], name='geospatial__recorde_7d0fa7_idx')],
            },
        ),
    ]
