# Generated by Django 5.2.17 on 2026-08-31 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0004_seed_document_evidence_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('OFFER', 'Offer'), ('PAYMENT', 'Payment'), ('TRANSACTION', 'Transaction'), ('DISPUTE', 'Dispute'), ('VERIFICATION', 'Verification'), ('DOCUMENT', 'Document'), ('DUE_DILIGENCE', 'Due diligence'), ('GEOSPATIAL', 'Geospatial'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=150)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parties.party')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'read_at', 'created_at'], name='notificatio_recipie_c84de5_idx'), models.Index(fields=['recipient_party', 'read_at'], name='notificatio_recipie_c9c298_idx'), models.Index(fields=['notification_type', 'resource_type', 'resource_id'], name='notificatio_notific_0965a7_idx'), models.Index(fields=['archived_at'], name='notificatio_archive_0625b4_idx')],
            },
        ),
    ]
