# Generated by Django 5.2.17 on 2026-08-26 10:42

from django.db import migrations


def create_default_roles(apps, schema_editor):

    Role = apps.get_model("parties", "Role")

    roles = [
        {
            "code": "ADMIN",
            "name": "Administrator",
            "description": "System administrator",
        },
        {
            "code": "SELLER",
            "name": "Seller",
            "description": "Can sell properties",
        },
        {
            "code": "BUYER",
            "name": "Buyer",
            "description": "Can purchase properties",
        },
    ]

    for role_data in roles:
        Role.objects.update_or_create(
            code=role_data["code"],
            defaults={
                "name": role_data["name"],
                "description": role_data["description"],
                "is_active": True,
            },
        )


def remove_default_roles(apps, schema_editor):

    Role = apps.get_model("parties", "Role")

    Role.objects.filter(
        code__in=[
            "ADMIN",
            "SELLER",
            "BUYER",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_roles,
            remove_default_roles,
        ),
    ]
