# Generated by Django 5.2.17 on 2026-08-31 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('offers', '0001_initial'),
        ('parties', '0004_seed_document_evidence_permissions'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING_PAYMENT', 'Pending payment'), ('PAYMENT_PROCESSING', 'Payment processing'), ('PAYMENT_COMPLETED', 'Payment completed'), ('DOCUMENTATION', 'Documentation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='INITIATED', max_length=30)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_transactions', to='parties.party')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='listings.listing')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='offers.offer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='properties.property')),
                ('seller_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_transactions', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='PENDING', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_transfer_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_checklist_items', to='parties.party')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='transactions.transaction')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_d2f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer_party', 'status'], name='transaction_buyer_p_6faaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller_party', 'status'], name='transaction_seller__74abd4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['property', 'status'], name='transaction_propert_29687f_idx'),
        ),
        migrations.AddIndex(
            model_name='transferchecklistitem',
            index=models.Index(fields=['transaction', 'status'], name='transaction_transac_e1eb91_idx'),
        ),
        migrations.AddIndex(
            model_name='transferchecklistitem',
            index=models.Index(fields=['position'], name='transaction_positio_633b63_idx'),
        ),
    ]
