# Generated by Django 5.2.17 on 2026-08-31 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_document_documents_d_propert_8ed4b0_idx_and_more'),
        ('listings', '0001_initial'),
        ('parties', '0004_seed_document_evidence_permissions'),
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('PAYMENT', 'Payment'), ('VERIFICATION', 'Verification'), ('DOCUMENT', 'Document'), ('LISTING', 'Listing'), ('PROPERTY', 'Property'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution_summary', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='listings.listing')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to='parties.party')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments.payment')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='properties.property')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='disputes.dispute')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence_items', to='documents.document')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence_items', to='documents.evidence')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_dispute_evidence', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_dispute_evidence', to='parties.party')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('author_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_messages', to='parties.party')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'priority'], name='disputes_di_status_3dbe35_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['transaction', 'status'], name='disputes_di_transac_5d8e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['payment', 'status'], name='disputes_di_payment_444005_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['property', 'status'], name='disputes_di_propert_5a12e3_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['opened_by_party', 'status'], name='disputes_di_opened__56bfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_b418ef_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['submitted_by_party', 'created_at'], name='disputes_di_submitt_79cfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_933084_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['author_party', 'created_at'], name='disputes_di_author__50b010_idx'),
        ),
    ]
