# Generated by Django 5.2.17 on 2026-08-31 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Identity'), ('PARTY', 'Party'), ('PROPERTY', 'Property'), ('LISTING', 'Listing'), ('OFFER', 'Offer'), ('TRANSACTION', 'Transaction'), ('PAYMENT', 'Payment'), ('DISPUTE', 'Dispute'), ('NOTIFICATION', 'Notification'), ('GEOSPATIAL', 'Geospatial'), ('DUE_DILIGENCE', 'Due diligence'), ('DOCUMENT', 'Document'), ('VERIFICATION', 'Verification'), ('AUTHORIZATION', 'Authorization'), ('ADMINISTRATION', 'Administration'), ('SYSTEM', 'System')], max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=150)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['category', 'action'], name='audit_audit_categor_6d6be4_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_audit_actor_i_023a4b_idx'), models.Index(fields=['occurred_at'], name='audit_audit_occurre_b8cdc4_idx')],
            },
        ),
    ]
