# Generated by Django 5.2.17 on 2026-08-25 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('property_type', models.CharField(choices=[('LAND', 'Land'), ('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('COMMERCIAL', 'Commercial'), ('OFFICE', 'Office'), ('FARM', 'Farm'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('UNDER_OFFER', 'Under offer'), ('SOLD', 'Sold'), ('RENTED', 'Rented'), ('RESERVED', 'Reserved'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=30)),
                ('ownership_basis', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_description', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('OWNER', 'Owner'), ('CLAIMANT', 'Claimant'), ('SELLER', 'Seller'), ('MANAGER', 'Manager')], max_length=30)),
                ('basis', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('OWERU_ESTABLISHED', 'Established by Oweru'), ('USER_SUPPLIED', 'Supplied by user'), ('AUTHORITY_OBTAINED', 'Obtained from authority')], max_length=30)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_relationships', to='parties.party')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
