export const routePaths = {
  home: '/',
  properties: '/properties',
  propertyDetail: '/properties/:propertyId',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  onboarding: '/account/onboarding',
  dashboard: '/dashboard',
  savedProperties: '/dashboard/saved-properties',
  messages: '/dashboard/messages',
  transactions: '/dashboard/transactions',
  verifications: '/dashboard/verifications',
  documents: '/dashboard/documents',
  profile: '/dashboard/profile',
  settings: '/dashboard/settings',
  seller: '/dashboard/seller',
  sellerProperties: '/dashboard/seller/properties',
  sellerPropertyNew: '/dashboard/seller/properties/new',
  sellerPropertyDetail: '/dashboard/seller/properties/:propertyId',
  sellerPropertyEdit: '/dashboard/seller/properties/:propertyId/edit',
  sellerPropertyDocuments: '/dashboard/seller/properties/:propertyId/documents',
  sellerListings: '/dashboard/seller/listings',
  sellerListingNew: '/dashboard/seller/listings/new',
  sellerListingDetail: '/dashboard/seller/listings/:listingId',
  sellerListingEdit: '/dashboard/seller/listings/:listingId/edit',
  sellerVerifications: '/dashboard/seller/verifications',
  verificationWorkspace: '/dashboard/verification-workspace',
  verificationDetail: '/verification/:verificationId',
} as const

export type AppRoutePath = (typeof routePaths)[keyof typeof routePaths]
