# Generated by Django 5.2.17 on 2026-08-25 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('TITLE', 'Title document'), ('OWNERSHIP', 'Ownership document'), ('TAX', 'Tax document'), ('IDENTITY', 'Identity document'), ('SURVEY', 'Survey document'), ('OTHER', 'Other')], max_length=30)),
                ('source_type', models.CharField(choices=[('OWERU_ESTABLISHED', 'Established by Oweru'), ('USER_SUPPLIED', 'Supplied by user'), ('AUTHORITY_OBTAINED', 'Obtained from authority')], max_length=30)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=30)),
                ('file_reference', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sighted_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
