# Generated by Django 5.2.17 on 2026-08-31 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentreview_evidence'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['property', 'status'], name='documents_d_propert_8ed4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['property', 'source_type'], name='documents_e_propert_cf16a9_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['recorded_at'], name='documents_e_recorde_67d49f_idx'),
        ),
    ]
