# Generated by Django 5.2.17 on 2026-08-31 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0004_seed_document_evidence_permissions'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('VERIFICATION_FEE', 'Verification fee'), ('DUE_DILIGENCE_FEE', 'Due diligence fee'), ('PROFESSIONAL_FEE', 'Professional fee'), ('RESERVATION_FEE', 'Reservation fee'), ('TRANSACTION_SUPPORT_FEE', 'Transaction support fee'), ('PURCHASE_PRICE_RECORD', 'Purchase price record'), ('OTHER', 'Other')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('MOBILE_MONEY', 'Mobile money'), ('GATEWAY', 'Gateway'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30)),
                ('external_reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('payee_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='parties.party')),
                ('payer_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='parties.party')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='parties.party')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction', 'status'], name='payments_pa_transac_a57bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_party', 'status'], name='payments_pa_payer_p_03d17f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purpose', 'status'], name='payments_pa_purpose_8579eb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_reference'], name='payments_pa_externa_e30da4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='payments_re_receipt_8aa2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['issued_to', 'issued_at'], name='payments_re_issued__7e469a_idx'),
        ),
    ]
